### PR TITLE
Rebuild as server

### PR DESCRIPTION
**Pull request by agarzola**
So close… sooo close.

### CODE REVIEW

**Comment by agarzola** [comment]
Koa is proving more difficult to work with than I expected, so it looks like I’ll be switching this to use Express.

**Comment by agarzola** [comment]
This is working pretty well running it locally. I’ve shut down my local server, so the command won’t work anymore until the deployment scripts are ready. There is one item we need to address before deployment, and that is user input sanitization. I’m not terribly knowledgeable re: security, so I’d like some input in this regard.

The user enters the following command:
```
/project make unicorns a reality
```

We receive `make unicorns a reality` as a string in a `POST` request body. We use that string in a Node.js `fs.appendFile()` method, like so:
https://github.com/devanooga/devanoobot/blob/809034397a5ba6ecd78c6b1ecd2603b56d3ab7a0/commands/project/append_to_file.js#L1-L14

How can this be abused?

**Comment by agarzola** [comment]
This is ready for review. I’ve added a working welcome message event handler and modified the welcome message a bit as well.

**Comment by StrangeWill** [comment]
You're a machine, I'll check this out next hacknight at the latest.

**Comment by agarzola** [comment]
Awesome!

**Pull request merged**
